### ISSUE TITLE
Consumable keys

### ISSUE THREAD

**Issue by ReshiStar** [Skyost/SerialKey#10]
Could you please add the option for keys to be consumed when used?

**Comment by Skyost** [comment]
If you set the option `reusable-keys` to `false` then it should work.

**Comment by ReshiStar** [comment]
No, that doesnt work the same way, that only gives a key back when the locked item is destroyed. What I mean is that the key is used up when the locked item is accessed.

**Comment by Skyost** [comment]
Closed as a duplicate of #8.
