### ISSUE TITLE
Suggestions / bug / question

### ISSUE THREAD

**Issue by srnyx** [Skyost/SerialKey#22]
Suggestion 1: Adding the ability to lock barrels would be cool.
Suggestion 2: Also would be cool if you could change how many spots there are in the Bunch Of Keys item from the config.

Bug: I have my keys named and I put them in a Bunch Of Keys, then when I reopened the Bunch of Keys, they were renamed back to "Key".

Question: Does the plugin work on 1.16.x or 1.15.x?

**Comment by Skyost** [comment]
How are you running the plugin ?

**Comment by srnyx** [comment]
> How are you running the plugin ?

How do you mean?

**Comment by Skyost** [comment]
@srnyx Which platform ? Which Java version ? Which operating system ? Spigot or Sponge ? Which version ? ...

**Comment by srnyx** [comment]
Platform? | 1.14 | Operating system? | Paper-Spigot | v1.0.3

_Sorry I don't really know what most of it means cause I use a server host (GGServers, 1 GB)_

**Comment by Skyost** [comment]
Suggestion 2 is impossible as lore is limited in size. The other ones have been added tho, I need to test it before releasing it.
