### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by Lorenzo0111** [Skyost/SerialKey#23]
Can you update the plugin? I need the 1.15.2 version

**Comment by Skyost** [comment]
[Its on the road](https://github.com/Skyost/SerialKey/commit/39736c3359d8485f1e3dacbbdda3266da009d6e2), but I don't have the time to test it for the moment.

**Comment by Lorenzo0111** [comment]
Okay

**Comment by GamerMedic** [comment]
Any news?

**Comment by Skyost** [comment]
Same state for the moment 😥    
But if you can test it, feel free to do so !

**Comment by Lorenzo0111** [comment]
Okay

**Comment by EndreEndi** [comment]
Can someone make a .jar? i don't know how to compile it :(
i use this plugin on my 1.16.5 PaperMC server and it works very well, 0 issues far as i'm consurned :)

**Comment by Lorenzo0111** [comment]
Ok, the latest version (  https://dev.bukkit.org/projects/serial-key/files/2726906  ) works on 1.16.5

**Comment by Skyost** [comment]
@Lorenzo0111 Did you have tested it ?

**Comment by Lorenzo0111** [comment]
yes
