### ISSUE TITLE
[Bug] Duplicate keys with "bunch of keys"

### ISSUE THREAD

**Issue by IdaEdz** [Skyost/SerialKey#3]
I tested this mod for the first time today. 

I found a unexpected behaviour (I think at least). I crafted a stack of "bunch of keys". Then I right-clicked the stack. I put in my key. Then I spread out the stack in my inventory and for every "bunch of keys" I have a copy of the key.

I think you get the point.

**Comment by Skyost** [comment]
The plugin will be updated in august :wink:
