### ISSUE TITLE
Key question

### ISSUE THREAD

**Issue by randombyte-developer** [Skyost/SerialKey#5]
Hi!

I have just seen the release of the Sponge counterpart at Ore. Without having the plugin tested but by reading the code, I suspect that the key items are identified by their name. Is that correct? If that is the case, a player could renamed any item with the correct item type to the key name to unlock a door/etc. Or am I wrong?

**Comment by Skyost** [comment]
Key items are identified by their names yes (but also by their type); it is not possible to identify them by any other mean. But, to unlock a padlock, the key must have a [specific lore](https://github.com/Skyost/SerialKey/blob/master/core/src/main/java/fr/skyost/serialkey/core/unlocker/LoreUnlocker.java#L93) which is not possible to add in-game.

Did I have answered your question ?

**Comment by randombyte-developer** [comment]
It might be worth to look into the [DataAPI](https://docs.spongepowered.org/stable/en/plugin/data/index.html) or use NBT data directly.

**Comment by Skyost** [comment]
Yes I thought about that, but the problem is that the plugin should be Bukkit compatible; and (sadly) Bukkit doesn't provide this kind of API.

**Comment by randombyte-developer** [comment]
Ah ok.
