### ISSUE TITLE
Key cloning isn't working

### ISSUE THREAD

**Issue by vPrapo** [Skyost/SerialKey#6]
Cloning keys isn't possible, when crafted I get normal key!
However this feature works with the older version SerialKey v0.4
but not with the latest 1.0.1

**Comment by Skyost** [comment]
Are you on Sponge or on Bukkit ?

**Comment by vPrapo** [comment]
Bukkit

**Comment by Skyost** [comment]
Which version, what are your permissions, how did you come to that error, is there something in your console, ... ? Please add more details ^^

**Comment by vPrapo** [comment]
I tried the latest of 
Paper, Bukkit, Spigot
[1.13.2]
All same issue
the cloned keys comes normal keys
but with the older version SerialKey v0.4 cloning works fine

No console errors
I use LuckPerms [Tested With and Without it] and I'm OP
Also I tested with no other plugins in a clean server and as operator
Same issue



![2019-02-16_20-33-06](https://user-images.githubusercontent.com/47542625/52903128-71286a00-322a-11e9-8277-1de428252eeb.gif)

**Comment by Skyost** [comment]
Thank you. I'm going to check this tomorrow.

**Comment by Skyost** [comment]
[Done](https://dev.bukkit.org/projects/serial-key/files/2676347/download) (the link will be active when the file will be approved by the Bukkit staff).
